version: "3.9"
services:
  mobile:
    build:
      context: ..
      dockerfile: dev/Dockerfile.mobile
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    env_file: ../src/.env
